apiVersion: cataloga.io/v2
kind: Entity
metadata:
  id: 'example:entity'
  type: example.type
  name: 'Example Entity'
  labels: {  }
  tags:
    environment: dev
    lifecycle: ''
    owner: infra-team
    site: ''
    zone: ''
spec: {  }
