apiVersion: cataloga.io/v2
kind: Schema
metadata:
  id: relation.depends_on
  name: Depends On Relation
spec:
  kind: relation
  description: Generic dependency relation.
  required: []
  properties: {}
