apiVersion: cataloga.io/v2
kind: Schema
metadata:
  id: runs_on
  name: Runs on
spec:
  kind: relation
  description: Service runs on host-like resource.
  source_types:
    - service
  target_types:
    - host
  required: []
  properties: {}
