apiVersion: cataloga.io/v2
kind: Schema
metadata:
  id: uses
  name: Uses
spec:
  kind: relation
  description: Source resource uses target resource.
  source_types:
    - service
  target_types:
    - database
  required: []
  properties: {}
