<?php $record=is_array($relation['record']??null)?$relation['record']:[]; $metadata=is_array($record['metadata']??null)?$record['metadata']:[]; $spec=is_array($record['spec']??null)?$record['spec']:[]; $id=(string)($metadata['id']??''); $type=(string)($metadata['type']??''); $name=(string)($metadata['name']??''); $from=(string)($spec['from']??''); $to=(string)($spec['to']??''); $attributes=is_array($spec['attributes']??null)?$spec['attributes']:[]; $sourcePath=(string)($relation['sourcePath']??''); $formAction=$mode==='edit'&&$id!==''?'/relations/'.rawurlencode($id):'/relations'; ?>
<div class="panel"><h2><?= $mode==='edit'?'Edit Relation':'Create Relation' ?></h2>
<?php if (!empty($error)): ?><p class="pill error">Error: <?= h((string)$error) ?></p><?php endif; ?>
<form method="post" action="<?= h($formAction) ?>" class="form-stack"><input type="hidden" name="csrf_token" value="<?= h(csrf_token()) ?>">
<div class="field"><label>metadata.id</label><input name="id" value="<?= h($id) ?>" required></div>
<div class="field"><label>metadata.type</label><select name="type"><?php foreach (($relationTypes??[]) as $rt): ?><option value="<?= h($rt) ?>" <?= $rt===$type?'selected':'' ?>><?= h($rt) ?></option><?php endforeach; ?></select></div>
<div class="field"><label>metadata.name</label><input name="name" value="<?= h($name) ?>" required></div>
<div class="field"><label>spec.from</label><select name="from"><?php foreach (($entities??[]) as $e): ?><option value="<?= h((string)$e['id']) ?>" <?= (string)$e['id']===$from?'selected':'' ?>><?= h((string)$e['id']) ?></option><?php endforeach; ?></select></div>
<div class="field"><label>spec.to</label><select name="to"><?php foreach (($entities??[]) as $e): ?><option value="<?= h((string)$e['id']) ?>" <?= (string)$e['id']===$to?'selected':'' ?>><?= h((string)$e['id']) ?></option><?php endforeach; ?></select></div>
<details><summary>Advanced mode</summary><div class="field"><label>attributes JSON</label><textarea name="attributes"><?= h(format_json($attributes)) ?></textarea></div><div class="field"><label>sourcePath override</label><input name="sourcePath" value="<?= h($sourcePath) ?>"></div></details>
<button type="submit" class="primary-button">Create Change Session</button></form></div>
